---
- name: Configure WebServers on prod2
  hosts: prod2
  become: True
  tasks:
    - name: Install Nginx
      apt: name=nginx
    - name: Copy site index.html   C
      copy: src=~/repo2/index.html dest=/var/www/html
    - name: restart Nginx
      service: name=nginx state=restarted
